language: java
jdk: openjdk11
before_script:
  - chmod +x gradlew
  - ./gradlew assemble
script:
  - ./gradlew clean build
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)